### ISSUE TITLE
Switch user

### ISSUE THREAD

**Issue by RNACode** [gjcarneiro/yacron#18]
* Yet Another Cron version: N/A
* Python version: 3
* Operating System: Ubuntu

### Description
The native cron allow specify user. Any plans about this? 

`#<timing>   <user> <command>`
`11 * * * *  root   /usr/lib/command`

**Comment by gjcarneiro** [comment]
I agree, would be a nice feature to have in yacron.

**Comment by gjcarneiro** [comment]
I started work on this, but it's not polished enough.  If the process doesn't have permission to change to the target user, the asyncio main loop gets killled.  Might be an asyncio bug, not sure...
