### ISSUE TITLE
how can I stop yacron job?

### ISSUE THREAD

**Issue by km23630** [gjcarneiro/yacron#27]
* Yet Another Cron version: latest version
* Python version: 3.6
* Operating System: linux centos6

yacron is a very modern and useful program!
In crontab, I can use the -l and -e options to check or stop a running job.
yacron doesn't seem to offer that option.
Do I have to kill a process to stop a running yacron job? Or is there a better way?
I need your help :)

**Comment by gjcarneiro** [comment]
I'm afraid not, there is no better way.  Sending SIGTERM to yacron process itself will cause yacron to gracefully terminate: it waits indefinitely for any running subprocesses. (I normally run yacron in a docker container, which gets killed after 30 seconds anyway).

For the time being, just manually kill the process.

There was a feature request (#23) for adding an HTTP interface for controlling yacron, but neither the submitter nor myself have gotten around to doing it yet.

**Comment by km23630** [comment]
thank you!
All other cron-like programs provided only gui :(
I asked that question because I use ssh to connect to the server.


2019년 10월 4일 (금) 오후 10:37, Gustavo J. A. M. Carneiro <
notifications@github.com>님이 작성:

**Comment by gjcarneiro** [comment]
> crontab -e edits the user's crontab

If this is what you are looking for, you can just live edit the yacrontab.yaml file; yacron automatically reads this file once per minute, and applies it.

But removing a cron job from yacron doesn't kill any existing processes that are still stuck running; those, you have to kill manually.

**Comment by gjcarneiro** [comment]
To stop yacron, send SIGTERM or SIGINT.  Those two signals are handled specially.  That's it, really.
