### ISSUE TITLE
Feature Request: Healthcheck endpoint

### ISSUE THREAD

**Issue by servo1x** [gjcarneiro/yacron#32]
Hi,

We would like to have a formal healthcheck endpoint but do not want to log the request to stdout if the response is 200.

Thanks!

**Comment by gjcarneiro** [comment]
You have `GET /version`.  And I don't think aiohttp allows selectively not logging certain requests.  Honestly, not worth the trouble to consider this feature (usefulness/work ratio way too low).  But if you send a PR and it's clean, I may consider it.
