### ISSUE TITLE
email: Missing required header field: "Date"

### ISSUE THREAD

**Issue by wodev** [gjcarneiro/yacron#39]
* Yet Another Cron version:  0.11.2
* Python version:                   3.8.7
* Operating System:             Alpine Linux 3.13.1

### Description

The spam filter amavisd  flags emails send by yacron with:
`
X-Amavis-Alert: BAD HEADER SECTION, Missing required header field: "Date"
`

`
INVALID HEADER: MISSING REQUIRED HEADER FIELD
Missing required header field: "Date"

 The RFC 5322 document specifies rules for forming internet messages.
 Section '3.6. Field Definitions' specifies that certain header fields
 are required (origination date field and the "From:" originator field).
`

### What I Did

yacron with configured email reporting.

**Comment by gjcarneiro** [comment]
Related Python bug: https://bugs.python.org/issue28879
