### ISSUE TITLE
Yacron HTTP server failing with: KeyError: "Key not found: 'Accept'"

### ISSUE THREAD

**Issue by vcajes** [gjcarneiro/yacron#45]
* Yet Another Cron version: 0.11.2
* Python version: the one bundled on the tagged [0.11.2](https://github.com/gjcarneiro/yacron/releases/tag/0.11.2) on the release page 
* Operating System: debian-stable

### Description

The web listen config fails to parse requests coming from the kubernetes health checks.

### What I Did

The yacron config

```
web:
  listen:
    - http://0.0.0.0:8072
```

The kubernetes healt check config:
```
        readinessProbe:
          httpGet:
            path: /status
            port: 8072
            scheme: HTTP
```

The output logs:

```
INFO:aiohttp.access:10.101.111.72 [22/Apr/2021:16:35:57 +0000] "GET /status HTTP/1.1" 500 244 "-" "kube-probe/1.19"
ERROR:aiohttp.server:Error handling request
Traceback (most recent call last):
  File "aiohttp/web_protocol.py", line 418, in start
  File "aiohttp/web_app.py", line 458, in _handle
  File "yacron/cron.py", line 182, in _web_get_status
  File "multidict/_multidict_py.py", line 74, in __getitem__
  File "multidict/_multidict_py.py", line 69, in getone
KeyError: "Key not found: 'Accept'"
```

Apparently it doesn't know how to pare the Accept header or something.

Thanks team!

**Comment by gjcarneiro** [comment]
Ah, yes, looking at the line in question, it is obvious that it would crash if the Accept header is missing.  Is a simple fix.

**Comment by gjcarneiro** [comment]
I made a new release 0.12.0.
