### ISSUE TITLE
Reload config without restart

### ISSUE THREAD

**Issue by akiryliuk** [gjcarneiro/yacron#49]
* Yet Another Cron version: latest
* Python version: latest
* Operating System: Debian 10

### Description

Can yacron reload configuration without restarting?
I want to deploy a new configuration and do not wait for yacron to stop and start again..
Because some script can run for several hours

**Comment by gjcarneiro** [comment]
Yes, it reloads config once per minute, right before checking which cron jobs need to start in the minute.

Only if there is a syntax error in the configuration does it ignore it.
