### ISSUE TITLE
TypeError: main() missing 1 required positional argument: 'loop'

### ISSUE THREAD

**Issue by bofm** [gjcarneiro/yacron#7]
* Yet Another Cron version: 0.4.1
* Python version: 3.6.2
* Operating System: Debian Jessie

### Description

`yacron` executable is not working.

### What I Did

```
$ pip install yacron
...
$ yacron -c /etc/crontab
Traceback (most recent call last):
  File "/usr/local/bin/yacron", line 11, in <module>
    sys.exit(main())
TypeError: main() missing 1 required positional argument: 'loop'
```

**Comment by gjcarneiro** [comment]
Wow, that's embarrassing, some refactoring I did for unit tests broke main.  Fixing...

**Comment by gjcarneiro** [comment]
Pushed a new release, yacron 0.4.2, that fixes this issue.
