### ISSUE TITLE
/etc/yacron.d is missing

### ISSUE THREAD

**Issue by andreas-wittig** [gjcarneiro/yacron#72]
* Yet Another Cron version:  yacron-0.17.0-x86_64-unknown-linux-gnu
* Python version:
* Operating System: Docker, Ubuntu-20

### Description

If the yacron-0.17.0-x86_64-unknown-linux-gnu is run without any option it returns:
"ERROR:yacron:Configuration error: [Errno 2] No such file or directory: '/etc/yacron.d'"

There ist no info at all about /etc/yacron.d.  What is expected there resp. what can be done there?

### What I Did
./yacron-0.17.0-x86_64-unknown-linux-gnu

**Comment by gjcarneiro** [comment]
By default, it expects `/etc/yacron.d` to be a directory containing one or more yacron config files.

If you have another config file path, use the `-c` option.

**Comment by andreas-wittig** [comment]
Oh, thank you for the quick response. 
My original approach was to search the term "yacron.d" in the docu - not any mention ... maybe that's worth a note.
Thank you again, merry christmas.

**Comment by gjcarneiro** [comment]
No, you're right.  The very fact that you had to ask this question means there is a UI problem.  Probably this means I need to improve that error message to explain this.  That's why I am not closing this bug.  Let's keep it open.

**Comment by gjcarneiro** [comment]
fixed in 0.18
