### ISSUE TITLE
Propose: permanent tasks

### ISSUE THREAD

**Issue by izatop** [gjcarneiro/yacron#77]
* Yet Another Cron version: 0.18.0
* Python version: 3.9.2
* Operating System: Linux

### Description

I run a permanent (infinity-running) task with `concurrencyPolicy: Forbid`.
This produce a warning:

`WARNING:yacron:Job task-name: still running and concurrencyPolicy is Forbid`

### Propose

It would be great to add `concurrencyPolicy: Permanent` (or something else) to  suppress the warning.

**Comment by gjcarneiro** [comment]
Question: would `schedule: @reboot` solve your problem? This would schedule a task to start once only, at startup, and will never again try to schedule it, so, no warning...

Unless your plan is to schedule it to start every minute, in case the process crashes...  In that case, it kind of starts to sound like a (poor) replacement for systemd or the like. :thinking:

**Comment by izatop** [comment]
Wow, `schedule: @reboot` is a cool feature. I take this for another case. 

And, yes, you're right, I wanted to use **yacron** as a process manager, partly. But after your answer, I think to use supervisor for my case.

Thanks a lot.
