### ISSUE TITLE
Rollbar Support

### ISSUE THREAD

**Issue by totalhack** [gjcarneiro/yacron#79]
### Description

I'd like the error reporting to support rollbar since we don't use Sentry. The email-based approach has been a bit unreliable for us (via gmail). 

Thanks!

**Comment by gjcarneiro** [comment]
Never heard of rollbar.  Keep in mind, you have the ability to run a shell command for notifications.  Look for this text in the README:
> The shell reporter (since yacron 0.13) executes a user given shell command in the specified shell ...

**Comment by totalhack** [comment]
OK, that should be sufficient, thanks.
